spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jsp_final_assignment
        username: root
        password: Wktks300djr@@ 
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      static-path-pattern: /resources/**
    web:
      resources:
        static-locations: file:/var/www/myapp/images/
security:
  jwt:
    secretKey: wcL9j01ir23NgiffvYLo2cwtHR7auPW0OGK02C6RlbQ=

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: Wktks300djr@@
    key-store-type: PKCS12
    key-alias: jspSpring