spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER_NAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      static-path-pattern: /resources/**
    web:
      resources:
        # 해당 부분은 이미지 DB가 javaSpring 내부에 저장되어 있다.
        # 해당 경로도 윈도우 환경에서 가져오도록 수정하면 어떻게 되지 않을까?
        # 이미지를 저장할 때 들어가는 경로가 db에서
        # DB는 테스트 디비와 실제 디비를 분리해서 테스트 해야 하는 거 아닌가?
        # DB를 수정해서 작업하는 부분은 주의를 해야 한다.
        static-locations: file:/var/www/myapp/images/
security:
  jwt:
    secretKey: ${JWT_SECRET_KEY}

server:
  port: ${SERVER_PORT}
  ssl:
    enabled: ${SERVER_SSL_ENABLED}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-store-type: ${SEVER_SSL_KEY_STORE_TYPE}
    key-alias: ${SERVER_SSL_KEY_ALIAS}

argon2:
  password:
    config:
      saltLength: 16
      hashLength: 32
      parallelism: 1
      memory: 60000
      iterations: 2