spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jsp_final_assignment
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
      static-path-pattern: /resources/**
    web:
      resources:
        static-locations: classpath:/static/images/

security:
  jwt:
    secretKey: wcL9j01ir23NgiffvYLo2cwtHR7auPW0OGK02C6RlbQ=